const fs = require('fs');
const path = require('path');

const ICONS_DIR = path.resolve(__dirname, '../../icons/dist');
const CATEGORIES_FILE = path.resolve(__dirname, '../../icons/categories.json');
const OUTPUT_FILE = path.resolve(__dirname, '../src/icons-data.ts');

const categories = JSON.parse(fs.readFileSync(CATEGORIES_FILE, 'utf-8'));

const iconsData = {};
const files = fs.readdirSync(ICONS_DIR).filter((f) => f.endsWith('.svg'));

for (const file of files) {
  const name = file.replace('.svg', '');
  const content = fs.readFileSync(path.join(ICONS_DIR, file), 'utf-8').trim();
  iconsData[name] = content;
}

const allBaseNames = [...new Set(Object.values(categories).flat())];

const output = `// Auto-generated by scripts/generate-icons.js – do not edit manually
export const iconsData: Record<string, string> = ${JSON.stringify(iconsData, null, 2)}

export const categories: Record<string, string[]> = ${JSON.stringify(categories, null, 2)}

export const allBaseNames: string[] = ${JSON.stringify(allBaseNames)}
`;

fs.writeFileSync(OUTPUT_FILE, output, 'utf-8');
console.log(
  `Generated ${Object.keys(iconsData).length} icons → src/icons-data.ts`
);
