import fs from 'fs-extra';
import path from 'path';

// Paths
const ICONS_DIR = 'dist/icons';
const BASE_CSS = 'src/styles/base.css';
const OUT_FILE = 'dist/lets-ui-icons.css';

// Helpers
function ensureSvgNamespace(svg) {
  if (svg.includes('xmlns=')) return svg;

  return svg.replace('<svg', '<svg xmlns="http://www.w3.org/2000/svg"');
}

// Build
async function run() {
  // Base CSS
  const baseCss = await fs.readFile(BASE_CSS, 'utf8');

  // SVGs
  const files = await fs.readdir(ICONS_DIR);
  const svgs = files.filter((f) => f.endsWith('.svg'));

  const icons = {};

  for (const file of svgs) {
    const isSolid = file.endsWith('-solid.svg');
    const name = file.replace('-solid.svg', '').replace('.svg', '');

    if (!icons[name]) {
      icons[name] = {};
    }

    icons[name][isSolid ? 'solid' : 'outline'] = file;

    // XMLNS
    const filePath = path.join(ICONS_DIR, file);
    const svg = await fs.readFile(filePath, 'utf8');
    const fixedSvg = ensureSvgNamespace(svg);

    if (fixedSvg !== svg) {
      await fs.writeFile(filePath, fixedSvg);
    }
  }

  // Icon generation
  let iconsCss = '';

  for (const [name, variants] of Object.entries(icons)) {
    if (variants.outline) {
      iconsCss += `
.lui.lui-${name} {
  background-color: currentColor;
  mask-image: url('icons/${variants.outline}');
  -webkit-mask-image: url('icons/${variants.outline}');
}
`;
    }

    if (variants.solid) {
      iconsCss += `
.lui-solid.lui-${name} {
  background-color: currentColor;
  mask-image: url('icons/${variants.solid}');
  -webkit-mask-image: url('icons/${variants.solid}');
}
`;
    }
  }

  // Final bundle
  const finalCss =
    `
/* ----------------------------------------------- *
 *  Autogenerated by Let's UI Icons. DO NOT EDIT!  *
 * ----------------------------------------------- */

${baseCss}${iconsCss}
`.trim() + '\n';

  await fs.ensureDir(path.dirname(OUT_FILE));
  await fs.writeFile(OUT_FILE, finalCss);

  console.log('✅ Successfully generated');
}

run().catch((err) => {
  console.error('❌ Error generating icons');
  console.error(err);
});
