import fs from 'fs-extra';
import path from 'path';
import { createRequire } from 'module';

const require = createRequire(import.meta.url);

const ICONS_PKG_DIR = path.dirname(
  require.resolve('@lets-ui/icons/package.json')
);
const ICONS_SRC = path.join(ICONS_PKG_DIR, 'dist');
const CATEGORIES_FILE = path.join(ICONS_PKG_DIR, 'categories.json');
const ICONS_DEST = 'dist/icons';
const BASE_CSS_SRC = 'src/styles/base.css';
const OUT_DIR = 'dist';

const HEADER = `/* ----------------------------------------------- *
 *  Autogenerated by Let's UI Icons. DO NOT EDIT!  *
 * ----------------------------------------------- */\n\n`;

function ensureSvgNamespace(svg) {
  if (svg.includes('xmlns=')) return svg;
  return svg.replace('<svg', '<svg xmlns="http://www.w3.org/2000/svg"');
}

function iconRules(icons) {
  let css = '';
  for (const [name, variants] of Object.entries(icons)) {
    if (variants.outline) {
      css += `.lui.lui-${name} {\n  background-color: currentColor;\n  mask-image: url('icons/${variants.outline}');\n  -webkit-mask-image: url('icons/${variants.outline}');\n}\n\n`;
    }
    if (variants.solid) {
      css += `.lui-solid.lui-${name} {\n  background-color: currentColor;\n  mask-image: url('icons/${variants.solid}');\n  -webkit-mask-image: url('icons/${variants.solid}');\n}\n\n`;
    }
  }
  return css;
}

async function run() {
  await fs.ensureDir(ICONS_DEST);
  await fs.copy(ICONS_SRC, ICONS_DEST);

  const files = await fs.readdir(ICONS_DEST);
  const svgs = files.filter((f) => f.endsWith('.svg'));

  const allIcons = {};

  for (const file of svgs) {
    const isSolid = file.endsWith('-solid.svg');
    const name = file.replace('-solid.svg', '').replace('.svg', '');

    if (!allIcons[name]) allIcons[name] = {};
    allIcons[name][isSolid ? 'solid' : 'outline'] = file;

    const filePath = path.join(ICONS_DEST, file);
    const svg = await fs.readFile(filePath, 'utf8');
    const fixed = ensureSvgNamespace(svg);
    if (fixed !== svg) await fs.writeFile(filePath, fixed);
  }

  const categories = JSON.parse(await fs.readFile(CATEGORIES_FILE, 'utf8'));
  const baseCss = await fs.readFile(BASE_CSS_SRC, 'utf8');

  const iconToCategory = {};
  for (const [cat, list] of Object.entries(categories)) {
    for (const name of list) iconToCategory[name] = cat;
  }

  const grouped = {};
  for (const [name, variants] of Object.entries(allIcons)) {
    const cat = iconToCategory[name] ?? 'misc';
    if (!grouped[cat]) grouped[cat] = {};
    grouped[cat][name] = variants;
  }

  // base.css — shared rules only
  await fs.writeFile(path.join(OUT_DIR, 'base.css'), HEADER + baseCss);

  // {category}.css — base + icons for that category
  for (const [cat, icons] of Object.entries(grouped)) {
    const content =
      (HEADER + baseCss + '\n' + iconRules(icons)).trimEnd() + '\n';
    await fs.writeFile(path.join(OUT_DIR, `${cat}.css`), content);
    console.log(`✔ ${cat}.css (${Object.keys(icons).length} icons)`);
  }

  // index.css — base + all icons
  const allRules = Object.values(grouped).map(iconRules).join('');
  const index = (HEADER + baseCss + '\n' + allRules).trimEnd() + '\n';
  await fs.writeFile(path.join(OUT_DIR, 'index.css'), index);

  console.log('✅ Successfully generated');
}

run().catch((err) => {
  console.error('❌ Error generating icons');
  console.error(err);
});
