import fs from 'fs-extra';
import path from 'path';
import { createRequire } from 'module';

const require = createRequire(import.meta.url);

const ICONS_PKG_DIR = path.dirname(
  require.resolve('@lets-ui/icons/package.json')
);
const ICONS_SRC = path.join(ICONS_PKG_DIR, 'dist');
const ICONS_DEST = 'dist/icons';
const BASE_CSS = 'src/styles/base.css';
const OUT_FILE = 'dist/lets-ui-icons.css';

function ensureSvgNamespace(svg) {
  if (svg.includes('xmlns=')) return svg;
  return svg.replace('<svg', '<svg xmlns="http://www.w3.org/2000/svg"');
}

async function run() {
  await fs.ensureDir(ICONS_DEST);
  await fs.copy(ICONS_SRC, ICONS_DEST);

  const baseCss = await fs.readFile(BASE_CSS, 'utf8');
  const files = await fs.readdir(ICONS_DEST);
  const svgs = files.filter((f) => f.endsWith('.svg'));

  const icons = {};

  for (const file of svgs) {
    const isSolid = file.endsWith('-solid.svg');
    const name = file.replace('-solid.svg', '').replace('.svg', '');

    if (!icons[name]) icons[name] = {};
    icons[name][isSolid ? 'solid' : 'outline'] = file;

    const filePath = path.join(ICONS_DEST, file);
    const svg = await fs.readFile(filePath, 'utf8');
    const fixedSvg = ensureSvgNamespace(svg);

    if (fixedSvg !== svg) await fs.writeFile(filePath, fixedSvg);
  }

  let iconsCss = '';

  for (const [name, variants] of Object.entries(icons)) {
    if (variants.outline) {
      iconsCss += `
.lui.lui-${name} {
  background-color: currentColor;
  mask-image: url('icons/${variants.outline}');
  -webkit-mask-image: url('icons/${variants.outline}');
}
`;
    }

    if (variants.solid) {
      iconsCss += `
.lui-solid.lui-${name} {
  background-color: currentColor;
  mask-image: url('icons/${variants.solid}');
  -webkit-mask-image: url('icons/${variants.solid}');
}
`;
    }
  }

  const finalCss =
    `
/* ----------------------------------------------- *
 *  Autogenerated by Let's UI Icons. DO NOT EDIT!  *
 * ----------------------------------------------- */

${baseCss}${iconsCss}
`.trim() + '\n';

  await fs.ensureDir(path.dirname(OUT_FILE));
  await fs.writeFile(OUT_FILE, finalCss);

  console.log('✅ Successfully generated');
}

run().catch((err) => {
  console.error('❌ Error generating icons');
  console.error(err);
});
